### PR TITLE
fix compilation error for newer glibc

### PR DESCRIPTION
**Pull request by 251**
That patch defines a missing macro introduced in v2.25: https://fossies.org/diffs/glibc/2.24_vs_2.25/include/limits.h-diff.html

### CODE REVIEW

**Comment by 251** [comment]
I just realised that the klee-uclibc tag that we use in Travis (KLEE) is outdated by 4 years and this is already fixed...

**Comment by ccadar** [comment]
@251 , I'm not sure I understand, are you saying this is fixed in the uclibc mainline, and we should try to rebase?

**Comment by 251** [comment]
@ccadar See KLEE's travis script: https://github.com/klee/klee/blob/master/.travis.yml - there we use mostly tag `klee_uclibc_v1.0.0` for klee-uclibc. But this references a very old commit from 2013 and not head of `klee_0_9_29`. We should update the travis script and maybe add a new tag to the last klee-uclibc commit. E.g. the glibc macro bug was fixed in #9.

**Comment by ccadar** [comment]
I see, thanks.  If you could open a PR for the Travis CI script, that would be great, I see no reason to use an old version.

**Pull request closed without merging**
