### PR TITLE
Enables proper locale support for  uclibc

### PR DESCRIPTION
**Pull request by MartinNowack**
Beside the configuration changes it also needs a backport from @aldot

### CODE REVIEW

**Comment by ccadar** [comment]
Hi @MartinNowack , do you know why this fails with `CMake Error at CMakeLists.txt:404 (message):
  Can't find "gperftools/malloc_extension.h"`?

**Comment by MartinNowack** [comment]
@ccadar Old buildscript: it does not install tcmalloc as a dependency which we enabled by default in: https://github.com/klee/klee/pull/931

**Comment by ccadar** [comment]
I see, I guess we need to update that too.

**Comment by MartinNowack** [comment]
@ccadar For now, I'll just disable tcmalloc. That should be fine. This is more for testing if it compiles

**Comment by ccadar** [comment]
Makes sense.

**Comment by MartinNowack** [comment]
Let's wait for #21

**Comment by ccadar** [comment]
@MartinNowack but I thought you'd only disable `tcmalloc` for this PR.  I think in general we'd like to enable it if it's the default in KLEE now, no?

**Comment by MartinNowack** [comment]
@ccadar This is only for the travis build for uclibc. This is independent of the builds of KLEE itself.
The `tcmalloc` is a sane default for memory limits beyond 3GB we don't scratch that limit in our test cases.

**Comment by ccadar** [comment]
@MartinNowack , just a quick reminder to rebase this PR.  Thanks!

**Comment by MartinNowack** [comment]
@ccadar Rebased and tests went through. Ready to be merged.

**Comment by ccadar** [comment]
Thanks again, @MartinNowack

**Pull request merged**
