### PR TITLE
Correcting use of 'lookForNew' and some rudimentary code tidying in 'configure'

### PR DESCRIPTION
**Pull request by aytey**
## Issue

I just tried (naïvely) building `klee-ulibc`, but very quickly got this issue:

```
[avj@tempvm klee-uclibc]$ ./configure -n
INFO:Configuring for native archive
INFO:Disabling assertions
INFO:Configuring for Debug build
INFO:Looking for...llvm-gcc
Traceback (most recent call last):
  File "./configure", line 627, in <module>
    main(sys.argv[1:])
  File "./configure", line 120, in main
    handleNativeConfig(pargs, cc)
  File "./configure", line 305, in handleNativeConfig
    cc=searchPath(cc, 'llvm-gcc')
  File "./configure", line 296, in searchPath
    logging.info('Could not find {}'.format(lookForNew))
NameError: global name 'lookForNew' is not defined
```

## Resolution

This PR fixes the above `NameError`, as well as making some high-level fixes as recommended by [`prospector`](https://pypi.org/project/prospector/).

After these changes:

```
[avj@tempvm klee-uclibc]$ ./configure -n
INFO:Configuring for native archive
INFO:Disabling assertions
INFO:Configuring for Debug build
INFO:Looking for...llvm-gcc
INFO:Could not find llvm-gcc
INFO:Looking for...clang
INFO:Found.../usr/bin/clang
INFO:Using CC.../usr/bin/clang
INFO:Checking for ncurses...
INFO:Removing template destination "/home/avj/clones/klee-uclibc/Makefile.klee"
INFO:Writing templated file to "/home/avj/clones/klee-uclibc/Makefile.klee"
WARNING:Removing existing config file.../home/avj/clones/klee-uclibc/.config
INFO:Setting up pre-made configure for...x86_64
INFO:Installing .config file
INFO:Looking for kernel include path...
INFO:Found "/usr/include"
```

Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

### CODE REVIEW

**Comment by aytey** [comment]
Travis seems unhappy, but it doesn't seem related to this change:

```
WARNING: The following packages cannot be authenticated!
2825  libz3 libz3-dev
2826E: There were unauthenticated packages and -y was used without --allow-unauthenticated
2827The command "${SRC_DIR}/.travis/klee.sh" exited with 100.
```

**Comment by ccadar** [comment]
Thanks, @andrewvaughanj this looks good, but we should fix the CI first.  
@MartinNowack would you like to do this given you authored the current CI scripts?  I assume the easiest thing would be just to add some of the build scripts from the main KLEE repo.  I would only bring the basic ones that would allow us to run some of the basic configurations with uclibc enabled.

**Comment by aytey** [comment]
> Thanks, @andrewvaughanj this looks good, but we should fix the CI first.

Completely reasonable :)

**Comment by ccadar** [comment]
@andrewvaughanj yes, the CI build scripts saw a major overhaul from @MartinNowack but we never updated them in this (slowly-moving) repo.  But now that they stopped working, we should do that.

**Comment by aytey** [comment]
"If it ain't broke, don't touch it" ... "oops, it broke" 😛

**Review by MartinNowack — DISMISSED** [review]
@andrewvaughanj I checked the code. Looks great, thanks for this PR.

**Comment by MartinNowack** [comment]
@ccadar Given the number of changes this repository has, I would rather give it a very, very, very low priority to fix the CI of this repository.
The code is still checked through KLEE's build process.
In the worst case, it might fail building mainline KLEE but this can be fixed timely in that case.

Otherwise, me trying it out locally took me less than two minutes.

**Comment by ccadar** [comment]
@MartinNowack But why not put in a basic script?  I don't think this is so hard, in the worst case we just copy everything from the main KLEE repo and enable a couple of targets only.  This would take 10 minutes and while it has several issues (duplication etc.) it's much better than not having a CI at all.

**Comment by MartinNowack** [comment]
@ccadar Added a working test environment again in #32 - we are ready to go again.

@andrewvaughanj Can you rebase your PR to make sure it passes the test suite.

**Comment by aytey** [comment]
> @andrewvaughanj Can you rebase your PR to make sure it passes the test suite.

Done!

**Review by ccadar — APPROVED** [review]

**Comment by ccadar** [comment]
Thanks again, @andrewvaughanj

**Pull request merged**
