### PR TITLE
Add a message when the bitcode compiler is specified via CC, to help …

### PR DESCRIPTION
**Pull request by ccadar**
…diagnose cases in which CC does not point to a valid bitcode compiler.

### CODE REVIEW

**Comment by ccadar** [comment]
@MartinNowack we seem to have some very old Travis CI scripts here.  I guess we should just copy the ones from KLEE?

**Comment by MartinNowack** [comment]
@ccadar Right, not only that. This travis script builds against LLVM 3.4.

**Review by MartinNowack — APPROVED** [review]
@ccadar Changes look fine for me!
This is ready.

Even build did not complete, I'm happy to approve this.
Thanks for your this PR.

**Comment by ccadar** [comment]
Thanks, @MartinNowack .  Since that's a trivial patch, let's merge it.  But we should fix Travis soon, I opened an new issue (#30).

**Pull request merged**
