### PR TITLE
Check if pointer size reflects architecture

### LINKED ISSUE #8: Replace platform.machine() with platform.architecture()
[`configure` uses platform.machine()](https://github.com/klee/klee-uclibc/blob/a8af87cdf58c27c57c654e864b3e6b76f7ed799b/configure#L144), but it needs to use platform.architecture() because the kernel might not match userspace.

Example:

```python
>>> platform.architecture()
('32bit', 'ELF')
>>> platform.machine()
'x86_64'
```

This is needed to build klee-uclibc inside a i386 Docker image container.

### PR DESCRIPTION
**Pull request by MartinNowack**
Add stronger check to validate if architecture and machine are
equivalent. Error out to inform user to invoke `make menuconfig`.

Avoids compiling for the wrong architecture (e.g. docker images).

Fixes #8.

### CODE REVIEW

**Comment by ccadar** [comment]
@MartinNowack This failure seems unrelated to your patch.

Do you plan to update the TravisCI checks first to be in sync with KLEE's?

**Comment by ccadar** [comment]
@MartinNowack Can you rebase and trigger a new CI check?

**Comment by MartinNowack** [comment]
@ccadar Rebased and Travis CI finished.

**Comment by ccadar** [comment]
Great, thanks @MartinNowack

**Pull request merged**
