### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by delcypher**
The main thing this fixes is a build issue related to my kernel version. I'd advise testing it on older machines because these changes might of broken builds on older kernels.

In addition the configure script now auto-detects to LLVMTOOLDIR so you are not forced to use the "Release+Asserts" build of LLVM in order to use klee-uclibc.

Once accepted (with any need modifications) we should update the KLEE documentation to instruct people to use this branch rather than the klee-uclibc tarball.

### CODE REVIEW

**Comment by MartinNowack** [comment]
@delcypher 
Can you use llvm-config as default and just overwrite the paths to the compilers with the optional flags?
This way, default llvm installation could be picked up automatically, which should help us in the long run.

According to removing the Makefile.config I agree with you. At least I don't see any direct usages either.
On the other hand, with `llvm-config --obj-root`, one can also get the path to the Makefile.config
So we could keep the detection logic of llvm and do not need to update/maintain it.

By the way, indeed - as you said - clang works great for building uclibc. I switched as well in the _llvm33 branch and cleaned up the patches. Works great.

**Comment by delcypher** [comment]
@MartinNowack : I've rewritten the configure script from scratch. Hopefully it will serve us better. Please don't merge yet, I have some other work I need to finish. Although please feel free to test the new `configure` script which should be fully functional (on this branch llvm-gcc and gcc4.8.2 work but clang3.3 fails currently).

Essentially @ccadar would like to be able support (at least on this legacy branch) x86_64 and i386 builds. I need to setup the configure script to copy the relevant `.config` (easy) and patch a few headers (urggh... this is nasty) based on the detected architecture.

For a newer version of klee-uclibc (i.e. on a new branch forked from 0.9.33) I would like to not have this mess and just make people run `make menuconfig` instead.

**Comment by MartinNowack** [comment]
Hey Dan - you've done a lot of work, great!!

Please have a look at the other branch as well, I just updated quite recently (it was a forced update, so please update your local copy).
Especially the header files issue should be fixed, you just need to copy the relevant .config file for you and make sure that your system has the linux header files installed. That should be it. Compiler is forced to pick up the right files. That should help to make some modifcations to your script.

By the way, I like the fact to finally get rid of Rules.mak.llvm and just have one Rules.mak file.
Maybe instead of the .in file approach you used, you can also include an additional Makefile in the Rules.mak which is modified by your configure script. I would be in favor for that as upstream changes are easier to manage and to apply in this case.

I'll try to test it later. Keep me posted and thanks!

**Comment by delcypher** [comment]
@MartinNowack Thanks for the suggestion.

I've modified the configure script so `Rules.mak` have minimal changes by simply including a file `Makefile.klee` that is created by the configure script.

Please take a look (Warning: I did a force push recently). If you're happy with this I'll do a rebase to clean up these commits. I'll then take a look at putting this configure script in the `klee_monolithic_llvm33` branch.

**Pull request merged**
