### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by MartinNowack**

### CODE REVIEW

**Comment by MartinNowack** [comment]
@ccadar That was easier than expected. Works as we discussed, no direct duplication of the build script needed, instead we use the build script from KLEE's repository.

If you find some time, please merge.

**Comment by ccadar** [comment]
@MartinNowack Thanks, but this doesn't seem to trigger any checks.

**Comment by MartinNowack** [comment]
@ccadar I know, which is strange - because here it works: https://github.com/MartinNowack/klee-uclibc/actions

There it works successfully, so maybe we try and fix things after that if something is missing.

**Comment by ccadar** [comment]
@MartinNowack But I can't see why merging this as it is will solve the issue, is this what you propose?

**Comment by MartinNowack** [comment]
@ccadar Luck ;) I don't see any difference between the this repository and mine - it's the same.
If you look at the diff, there is no difference to this branch/repository. The only thing I can imagine is that the default branch is another one here. But this shouldn't make a difference.

**Comment by MartinNowack** [comment]
@ccadar I'll try to push the branch as part of this repository - this might make a difference

**Comment by MartinNowack** [comment]
@ccadar Yes, that makes the difference ;) And thinking about it, that makes sense. From a security point of view, you could otherwise extract arbitrary things with a forked repository.

**Comment by MartinNowack** [comment]
@ccadar All checks passed - woohoo.

**Review by ccadar — APPROVED** [review]
Cool, thanks!

**Pull request merged**
