### PR TITLE
[TravisCI] Updated Travis-CI to compile KLEE with CMake only

### PR DESCRIPTION
**Pull request by andreamattavelli**

### CODE REVIEW

**Comment by MartinNowack** [comment]
@andreamattavelli One question, the KLEE repository provides already all the .travis files to setup KLEE. Can we reuse them here as well? Less to maintain and less to update.

**Comment by andreamattavelli** [comment]
As I already mentioned to Dan, it is currently not possible. The travis ci script assumes the location of the code. We would need a big refactoring..

**Comment by MartinNowack** [comment]
Why not doing it in 2 steps: First git clone klee; 2. ${SRC_DIR}/klee/.travis/execute_fancy_script.sh?

> As I already mentioned to Dan, it is currently not possible. The travis ci script assumes the location of the code. We would need a big refactoring..
>

**Comment by MartinNowack** [comment]
Ahh, wait - now I got it. True.

**Comment by andreamattavelli** [comment]
@MartinNowack Right. It is doable, so feel free to do it if you want :)

**Comment by ccadar** [comment]
I propose we merge this, and then we can try to improve this later.

**Comment by MartinNowack** [comment]
Agreed.

**Pull request merged**
